### ISSUE TITLE
[Bug] Problems With Fancy menu

### ISSUE THREAD

**Issue by epicyeeto** [BloCamLimb/ModernUI#72]
**Describe the bug**
Modern UI does not work with FancyMenu Mod

**To Reproduce**
Just Change the menu a bit with Fancymenu mod and then use it with modern UI then you will see the problem and did not change the settings menu

**Expected behavior**
expected it to only change the font 

**Screenshots**
![image](https://user-images.githubusercontent.com/73504007/128660124-46240063-2991-4c82-882d-8e4580568a81.png)

**Environment**
 - Mod Version:ModernUI-1.16.5-2.5.1.86-universal.jar
 - Forge Version: 36.2.2
 - Operating System: Windows
 - Graphics Card: rtx 3060 ti
 - Other Mods: 260 other mods

**Comment by BloCamLimb** [comment]
Modern UI does not change the setting menu, this is not a bug

**Comment by epicyeeto** [comment]
fixed just had to replace stuff

**Comment by epicyeeto** [comment]
its not it randomizes it when you leave world

**Comment by BloCamLimb** [comment]
I still don't understand what you think doesn't work properly

**Comment by epicyeeto** [comment]
The start menu when you launch the game

**Comment by epicyeeto** [comment]
it completely messes everything up in the menu

**Comment by epicyeeto** [comment]
and when you try to resorting it when you leave a world it completely unsorts it

**Comment by epicyeeto** [comment]
did you look at the photo

**Comment by BloCamLimb** [comment]
FancyMenu mod seems to be like this
